export type Medicine = {
  id: number;
  name: string;
  addToName?: string;
  ndc?: string;
  unitsInPen?: number;
  expire?: number;
  prime?: number;
  pensAmount?: number;
  dosage?: string;

  // SEO landing-page fields
  seoSlug?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoIntro?: string;
};

export const rawMedicineData: Medicine[] = [
  {
    id: 1,
    name: "Admelog U-100 Vial 10ml",
    addToName: "10ml per Vial",
    ndc: "NDC: 0024-5924-10",
    unitsInPen: 1000,
    expire: 28,
  },
  {
    id: 2,
    name: "Admelog SoloStar Pen U-100",
    addToName: "3ml per Pen, 15ml per Box",
    ndc: "NDC: 0024-5925-05",
    expire: 28,
    prime: 2,
    unitsInPen: 300,
    pensAmount: 5,
    seoSlug: "admelog-days-supply-calculator",
    seoTitle: "Admelog Days Supply Calculator with Priming",
    seoDescription:
      "Calculate Admelog insulin pen days supply including priming doses. Designed for pharmacists and pharmacy technicians.",
    seoIntro:
      "Use this Admelog days supply calculator to estimate insulin pen days supply while accounting for priming and real-world dispensing workflow.",
  },
  {
    id: 3,
    name: "Admelog U-100 3ml Vial",
    addToName: "3ml per Vial",
    ndc: "NDC: 0024-5926-05",
    expire: 28,
    unitsInPen: 300,
  },
  {
    id: 4,
    name: "Basaglar® KwikPen® U-100 5 Pens",
    addToName: "3ml per Cartridge, 15ml per Box",
    ndc: "NDC: 0002-7715-59",
    prime: 2,
    unitsInPen: 300,
    expire: 28,
    pensAmount: 5,
    seoSlug: "basaglar-days-supply-calculator",
    seoTitle: "Basaglar Days Supply Calculator with Priming",
    seoDescription:
      "Calculate Basaglar insulin pen days supply including priming doses for pharmacist audit-safe dispensing.",
    seoIntro:
      "Use this Basaglar calculator to determine accurate insulin days supply for pen dispensing, insurance billing, and pharmacy workflow.",
  },
  {
    id: 5,
    name: "Basaglar® Tempo Pen U-100 5 Pens",
    addToName: "3ml per Pen, 15ml per Box",
    ndc: "NDC: 0002-8214-05",
    prime: 2,
    unitsInPen: 300,
    expire: 28,
    pensAmount: 5,
  },
  {
    id: 6,
    name: "Apidra Cartridge U-100 5 Cartridges",
    addToName: "3ml per Cartridge, 15ml per Box",
    ndc: "NDC: 0088-2500-52",
    expire: 28,
    unitsInPen: 300,
    pensAmount: 5,
  },
  {
    id: 7,
    name: "Apidra 100 U/mL Vial",
    addToName: "10ml per Vial",
    ndc: "NDC: 0088-2500-33",
    expire: 28,
    unitsInPen: 1000,
  },
  {
    id: 8,
    name: "Apidra SoloStar Pen U-100 5 Pens",
    addToName: "3ml per Pen, 15ml per Box",
    ndc: "NDC: 0088-2502-05",
    expire: 28,
    unitsInPen: 300,
    prime: 2,
    pensAmount: 5,
    seoSlug: "apidra-days-supply-calculator",
    seoTitle: "Apidra Days Supply Calculator with Priming",
    seoDescription:
      "Calculate Apidra insulin pen days supply including priming doses. Built for pharmacists and pharmacy technicians.",
    seoIntro:
      "Use this Apidra calculator to estimate insulin pen days supply quickly and consistently while accounting for priming.",
  },
  {
    id: 9,
    name: "Fiasp U-100 Multi-dose Vial",
    addToName: "10ml per Vial",
    ndc: "NDC: 0169-3201-11",
    expire: 28,
    unitsInPen: 1000,
  },
  {
    id: 10,
    name: "Fiasp FlexTouch Pen U-100 5 Pens",
    addToName: "3ml per Pen, 15ml per Box",
    ndc: "NDC: 0169-3204-15",
    pensAmount: 5,
    expire: 28,
    prime: 2,
    unitsInPen: 300,
    seoSlug: "fiasp-days-supply-calculator",
    seoTitle: "Fiasp Days Supply Calculator with Priming",
    seoDescription:
      "Calculate Fiasp insulin pen days supply including priming doses for pharmacists.",
    seoIntro:
      "Use this Fiasp days supply calculator to estimate insulin pen days supply for dispensing, billing, and audit review.",
  },
  {
    id: 11,
    name: "Fiasp® PenFill® 5 Cartridges U-100",
    addToName: "3ml per Cartridge, 15ml per Box",
    ndc: "NDC: 0169-3205-15",
    pensAmount: 5,
    unitsInPen: 300,
    prime: 2,
    expire: 28,
  },
  {
    id: 12,
    name: "Fiasp® PumpCart® 5 Cartridges U-100",
    addToName: "1.6ml per Cartridge",
    ndc: "NDC: 0169-3206-15",
    pensAmount: 5,
    unitsInPen: 160,
    expire: 4,
  },
  {
    id: 13,
    name: "Humalog U-100 Vial 10ml",
    addToName: "10ml per Vial",
    ndc: "NDC: 0002-7510-01",
    prime: 0,
    unitsInPen: 1000,
    expire: 28,
  },
  {
    id: 15,
    name: "Humalog Cartridge U-100 5 Cartridges",
    addToName: "3ml per Cartridge, 15ml per Box",
    ndc: "NDC: 0002-7516-59",
    prime: 2,
    expire: 28,
    unitsInPen: 300,
    pensAmount: 5,
  },
  {
    id: 16,
    name: "Humalog Tempo Pen U-100 5 Pens",
    addToName: "3ml per Cartridge, 15ml per Box",
    ndc: "NDC: 0002-8213-05",
    prime: 2,
    expire: 28,
    unitsInPen: 300,
    pensAmount: 5,
  },
  {
    id: 17,
    name: "Humalog KwikPen U-100 5 Pens",
    addToName: "3ml per Pen, 15ml per Box",
    ndc: "NDC: 0002-8799-59",
    prime: 2,
    expire: 28,
    unitsInPen: 300,
    pensAmount: 5,
    seoSlug: "humalog-days-supply-calculator",
    seoTitle: "Humalog Days Supply Calculator with Priming",
    seoDescription:
      "Calculate Humalog insulin pen days supply including priming doses. Designed for pharmacists and pharmacy technicians.",
    seoIntro:
      "Use this Humalog days supply calculator to estimate insulin pen days supply while accounting for priming, package size, and pharmacy workflow.",
  },
  {
    id: 18,
    name: "Humalog KwikPen U-200 2 Pens",
    addToName: "3ml per Pen, 10ml per Box",
    ndc: "NDC: 0002-7712-27",
    prime: 2,
    expire: 28,
    unitsInPen: 600,
    pensAmount: 2,
  },
  {
    id: 19,
    name: "Humalog Junior KwikPen 5 Pens U-100",
    addToName: "3ml per Pen, 15ml per Box",
    ndc: "NDC: 00002-7714-59",
    prime: 2,
    expire: 28,
    unitsInPen: 300,
    pensAmount: 5,
  },
  {
    id: 20,
    name: "Humalog Mix 75/25 KwikPen 5 Pens U-100",
    addToName: "3ml per Pen, 15ml per Box",
    ndc: "NDC: 0002-8797-59",
    prime: 2,
    expire: 10,
    unitsInPen: 300,
    pensAmount: 5,
    seoSlug: "humalog-75-25-days-supply-calculator",
    seoTitle: "Humalog Mix 75/25 Days Supply Calculator with Priming",
    seoDescription:
      "Calculate Humalog Mix 75/25 insulin pen days supply including priming doses for pharmacists.",
    seoIntro:
      "Use this Humalog Mix 75/25 calculator to determine accurate insulin pen days supply for dispensing and insurance billing.",
  },
  {
    id: 21,
    name: "Humalog Mix 75/25 10ml Vial U-100",
    addToName: "10ml per Vial",
    ndc: "NDC: 0002-7511-01",
    expire: 28,
    unitsInPen: 1000,
  },
  {
    id: 22,
    name: "Humalog Mix 50/50 KwikPen 5 Pens U-100",
    addToName: "3ml per Pen, 15ml per Box",
    ndc: "NDC: 0002-8798-59",
    expire: 10,
    prime: 2,
    unitsInPen: 300,
    pensAmount: 5,
    seoSlug: "humalog-50-50-days-supply-calculator",
    seoTitle: "Humalog Mix 50/50 Days Supply Calculator with Priming",
    seoDescription:
      "Calculate Humalog Mix 50/50 insulin pen days supply including priming doses.",
    seoIntro:
      "Use this Humalog Mix 50/50 days supply calculator to estimate insulin pen days supply quickly and consistently.",
  },
  {
    id: 23,
    name: "Humalog Mix 50/50 U-100 Vial",
    addToName: "10ml per Vial",
    ndc: "NDC: 0002-7512-01",
    expire: 28,
    unitsInPen: 1000,
  },
  {
    id: 24,
    name: "Humulin N Vial U-100 3ml",
    addToName: "3ml per Vial",
    ndc: "NDC: 0002-8315-17",
    unitsInPen: 300,
    expire: 31,
  },
  {
    id: 25,
    name: "Humulin® N Vial U-100",
    addToName: "10ml per Vial",
    ndc: "NDC: 0002-8315-01",
    unitsInPen: 1000,
    expire: 31,
    prime: 0,
  },
  {
    id: 26,
    name: "Humulin® N KwikPen® U-100 5 Pens",
    addToName: "3ml per Pen, 15ml per Box",
    ndc: "NDC: 0002-8805-59",
    expire: 14,
    unitsInPen: 300,
    prime: 2,
    pensAmount: 5,
    seoSlug: "humulin-n-days-supply-calculator",
    seoTitle: "Humulin N Days Supply Calculator with Priming",
    seoDescription:
      "Calculate Humulin N insulin pen days supply including priming doses for pharmacist audit-safe dispensing.",
    seoIntro:
      "Use this Humulin N calculator to determine accurate insulin days supply for pen dispensing, insurance billing, and fast pharmacy workflow.",
  },
  {
    id: 27,
    name: "Humulin® R U-100 3ml Vial",
    addToName: "3ml per Vial",
    ndc: "NDC: 0002-8215-17",
    unitsInPen: 300,
    expire: 31,
  },
  {
    id: 28,
    name: "Humulin® R U-100 10ml Vial",
    addToName: "10ml per Vial",
    ndc: "NDC: 0002-8215-01",
    unitsInPen: 1000,
    expire: 31,
  },
  {
    id: 29,
    name: "Humulin® R U-500 Vial 20ml",
    addToName: "20ml per Vial",
    ndc: "NDC: 0002-8501-01",
    unitsInPen: 10000,
    expire: 40,
  },
  {
    id: 30,
    name: "Humulin® R U-500 KwikPen® 2 Pens",
    addToName: "3ml per Pen, 6ml per Box",
    ndc: "NDC: 0002-8824-27",
    expire: 28,
    unitsInPen: 1500,
    prime: 5,
    pensAmount: 2,
    seoSlug: "humulin-r-u500-days-supply-calculator",
    seoTitle: "Humulin R U-500 Days Supply Calculator with Priming",
    seoDescription:
      "Calculate Humulin R U-500 KwikPen days supply including priming doses for pharmacists.",
    seoIntro:
      "Use this Humulin R U-500 calculator to estimate days supply accurately for high-concentration insulin pen dispensing.",
  },
  {
    id: 31,
    name: "Humulin® 70/30 Vial U-100 10ml",
    addToName: "10ml per Vial",
    ndc: "NDC: 0002-8715-01",
    unitsInPen: 1000,
    expire: 31,
  },
  {
    id: 32,
    name: "Humulin® 70/30 KwikPen® 5 Pens U-100",
    addToName: "3ml per Pen, 15ml per Box",
    ndc: "NDC: 0002-8803-59",
    expire: 10,
    unitsInPen: 300,
    prime: 2,
    pensAmount: 5,
    seoSlug: "humulin-70-30-days-supply-calculator",
    seoTitle: "Humulin 70/30 Days Supply Calculator with Priming",
    seoDescription:
      "Calculate Humulin 70/30 insulin pen days supply including priming doses for pharmacists.",
    seoIntro:
      "Use this Humulin 70/30 calculator to estimate insulin pen days supply for dispensing, billing, and audit review.",
  },
  {
    id: 33,
    name: "Insulin Aspart (U-100) Vial 10 mL",
    addToName: "10 mL per Vial",
    ndc: "NDC: 73070-100-11",
    unitsInPen: 1000,
    expire: 28,
  },
  {
    id: 34,
    name: "Insulin Aspart Protamine-Insulin Aspart Mix 70/30 U-100 Vial10 mL",
    addToName: "10 mL per Vial",
    ndc: "NDC: 73070-200-11",
    unitsInPen: 1000,
    expire: 28,
  },
  {
    id: 35,
    name: "Insulin Aspart U-100 Cartridge 3mL (5-Pack)",
    addToName: "5 × 3 mL Cartridges per Box",
    ndc: "NDC: 73070-102-15",
    unitsInPen: 300,
    expire: 28,
    prime: 2,
    pensAmount: 5,
  },
  {
    id: 36,
    name: "Insulin Aspart Protamine–Aspart Mix 70/30 FlexPen (5 Pens)",
    addToName: "3 mL per Pen, 15 mL per Box",
    ndc: "NDC: 73070-203-15",
    unitsInPen: 300,
    pensAmount: 5,
    prime: 2,
    expire: 14,
  },
  {
    id: 37,
    name: "Insulin Aspart FlexPen 5 Pens U-100",
    addToName: "3mL per Pen, 5 Pens per Box",
    ndc: "73070-0103-15",
    unitsInPen: 300,
    pensAmount: 5,
    expire: 28,
    prime: 2,
  },
  {
    id: 70,
    name: "Insulin Glargine SoloStar U-300 3 Pens",
    ndc: "0955-3900-03",
    addToName: "1.5ml per Pen, 4.5ml per Box",
    unitsInPen: 450,
    pensAmount: 3,
    prime: 3,
    expire: 56,
  },
  {
    id: 38,
    name: "Insulin Glargine-YFGN U-100 Vial 10 mL",
    addToName: "10 mL per Vial",
    ndc: "NDC: 83257-0014-11",
    unitsInPen: 1000,
    expire: 28,
  },
  {
    id: 39,
    name: "Insulin Glargine-YFGN U-100 5 Pens 10mL",
    addToName: "3 mL per Pen, 5 Pens per Box",
    ndc: "NDC: 83257-0015-32",
    unitsInPen: 300,
    pensAmount: 5,
    expire: 28,
    prime: 2,
  },
  {
    id: 40,
    name: "Lantus® 10ml Vial U-100",
    addToName: "10ml per Vial",
    ndc: "NDC: 0088-5021-01 / 00088-2220-33",
    unitsInPen: 1000,
    expire: 28,
  },
  {
    id: 41,
    name: "Lantus® SoloStar 5 Pens U-100",
    addToName: "3ml per Pen, 15ml per Box",
    ndc: "NDC: 00088-2219-05",
    expire: 28,
    unitsInPen: 300,
    prime: 2,
    pensAmount: 5,
    seoSlug: "lantus-days-supply-calculator",
    seoTitle: "Lantus Days Supply Calculator with Priming",
    seoDescription:
      "Calculate Lantus SoloStar insulin pen days supply including priming doses. Built for pharmacists and pharmacy technicians.",
    seoIntro:
      "Use this Lantus calculator to estimate insulin pen days supply while accounting for priming, package size, and pharmacy workflow.",
  },
  {
    id: 42,
    name: "Lispro Vial U-100 10ml",
    addToName: "10ml per Vial",
    ndc: "NDC: 00002-7737-01",
    unitsInPen: 1000,
    expire: 28,
  },
  {
    id: 43,
    name: "Lispro U-100 Kwikpen 3ml 5 Pens",
    addToName: "3ml per pen, 15ml per Box",
    ndc: "NDC: 00002-8222-59",
    unitsInPen: 300,
    expire: 28,
    prime: 2,
    pensAmount: 5,
  },
  {
    id: 44,
    name: "Levemir® FlexTouch® 5 Pens U-100",
    addToName: "3ml per Pen, 15 ml per Box",
    ndc: "NDC: 0169-6434-10",
    expire: 42,
    unitsInPen: 300,
    pensAmount: 5,
    prime: 2,
    seoSlug: "levemir-days-supply-calculator",
    seoTitle: "Levemir Days Supply Calculator with Priming",
    seoDescription:
      "Calculate Levemir FlexTouch insulin pen days supply including priming doses for pharmacists.",
    seoIntro:
      "Use this Levemir calculator to determine insulin pen days supply accurately for dispensing and billing workflow.",
  },
  {
    id: 45,
    name: "Lispro Mix 75/25 KwikPen 5 Pens U-100",
    addToName: "3ml per Pen, 15 ml per Box",
    ndc: "NDC: 0002-8233-05",
    expire: 10,
    unitsInPen: 300,
    pensAmount: 5,
    prime: 2,
  },
  {
    id: 46,
    name: "Lispro JR U-100 3 ml KwikPen 5 Pens",
    addToName: "3ml per Pen, 15 ml per Box",
    ndc: "NDC: 0027-752-05",
    expire: 28,
    unitsInPen: 300,
    pensAmount: 5,
    prime: 2,
  },
  {
    id: 47,
    name: "Lispro U-100 100/ml  10ml Vial",
    addToName: "10ml per Vial",
    ndc: "NDC: 0169-1833-11",
    unitsInPen: 1000,
    expire: 42,
  },
  {
    id: 48,
    name: "Novolin® N Vial U-100 10ml",
    addToName: "10ml per Vial",
    ndc: "NDC: 0169-1834-11",
    unitsInPen: 1000,
    expire: 42,
  },
  {
    id: 49,
    name: "Novolin® N FlexPen® 5 Pens U-100",
    addToName: "3ml per Pen, 15ml per Box",
    ndc: "NDC: 0169-3004-15",
    prime: 2,
    unitsInPen: 300,
    expire: 28,
    pensAmount: 5,
    seoSlug: "novolin-n-days-supply-calculator",
    seoTitle: "Novolin N Days Supply Calculator with Priming",
    seoDescription:
      "Calculate Novolin N FlexPen days supply including priming doses for pharmacists.",
    seoIntro:
      "Use this Novolin N calculator to estimate insulin pen days supply quickly and consistently while accounting for priming.",
  },
  {
    id: 50,
    name: "Novolin® R Vial U-100 10ml",
    addToName: "10ml per Vial",
    ndc: "NDC: 0169-1833-11",
    unitsInPen: 1000,
    expire: 42,
  },
  {
    id: 51,
    name: "Novolin® R FlexPen® 5 Pens 100U",
    addToName: "3ml per Pen, 15ml per Box",
    ndc: "NDC: 0169-3003-25/00169-3003-15",
    prime: 2,
    unitsInPen: 300,
    expire: 28,
    pensAmount: 5,
    seoSlug: "novolin-r-days-supply-calculator",
    seoTitle: "Novolin R Days Supply Calculator with Priming",
    seoDescription:
      "Calculate Novolin R FlexPen days supply including priming doses for pharmacists.",
    seoIntro:
      "Use this Novolin R calculator to determine accurate insulin pen days supply for dispensing and billing workflow.",
  },
  {
    id: 52,
    name: "Novolin® 70/30 Vial U-100 10ml",
    addToName: "10ml per Vial",
    ndc: "NDC: 0169-1837-02 / 0169-1837-11",
    unitsInPen: 1000,
    expire: 42,
  },
  {
    id: 53,
    name: "Novolin® 70/30 FlexPen® 5 Pens U-100",
    addToName: "3ml per Pen, 15ml per Box",
    ndc: "NDC: 0169-3007-15",
    prime: 2,
    unitsInPen: 300,
    expire: 28,
    pensAmount: 5,
    seoSlug: "novolin-70-30-days-supply-calculator",
    seoTitle: "Novolin 70/30 Days Supply Calculator with Priming",
    seoDescription:
      "Calculate Novolin 70/30 FlexPen days supply including priming doses for pharmacists.",
    seoIntro:
      "Use this Novolin 70/30 calculator to estimate insulin pen days supply for pharmacy workflow, insurance billing, and audit review.",
  },
  {
    id: 54,
    name: "NovoLog® Vial U-100 10ml",
    addToName: "10ml per Vial",
    ndc: "NDC: 0169-7501-11",
    unitsInPen: 1000,
    expire: 28,
  },
  {
    id: 55,
    name: "NovoLog® FlexPen® 5 Pens U-100",
    addToName: "3ml per pen, 15ml per box",
    ndc: "NDC: 00169-6339-10",
    prime: 2,
    unitsInPen: 300,
    expire: 28,
    pensAmount: 5,
    seoSlug: "novolog-days-supply-calculator",
    seoTitle: "NovoLog Days Supply Calculator with Priming",
    seoDescription:
      "Calculate NovoLog FlexPen insulin days supply including priming doses. Designed for pharmacists and pharmacy technicians.",
    seoIntro:
      "Use this NovoLog days supply calculator to estimate insulin pen days supply while accounting for priming and real-world dispensing workflow.",
  },
  {
    id: 56,
    name: "NovoLog® PenFill® 5 Cartridges U-100",
    addToName: "3ml per cartridge, 15ml per box",
    ndc: "NDC: 0169-3303-12",
    prime: 2,
    unitsInPen: 300,
    expire: 28,
    pensAmount: 5,
  },
  {
    id: 57,
    name: "NovoLog® Mix 70/30 10ml Vial U-100",
    addToName: "10ml per Vial",
    ndc: "NDC: 0169-3685-12",
    unitsInPen: 1000,
    expire: 28,
  },
  {
    id: 58,
    name: "NovoLog® Mix 70/30 FlexPen® 5 Pens U-100",
    addToName: "3ml per Pen, 15ml per Box",
    ndc: "NDC: 0169-3696-19",
    prime: 2,
    unitsInPen: 300,
    expire: 14,
    pensAmount: 5,
    seoSlug: "novolog-70-30-days-supply-calculator",
    seoTitle: "NovoLog Mix 70/30 Days Supply Calculator with Priming",
    seoDescription:
      "Calculate NovoLog Mix 70/30 insulin pen days supply including priming doses for pharmacists.",
    seoIntro:
      "Use this NovoLog Mix 70/30 calculator to determine accurate insulin pen days supply for dispensing, billing, and audit review.",
  },
  {
    id: 59,
    name: "Semglee U-100 Vial 10 mL",
    addToName: "10 mL per Vial",
    ndc: "NDC: 83257-0011-11",
    unitsInPen: 1000,
    expire: 28,
  },
  {
    id: 60,
    name: "Semglee U-100 Pen 3mL 5 Pens",
    addToName: "3 mL per Pen, 15ml per Box",
    ndc: "NDC: 83257-0012-33",
    unitsInPen: 300,
    pensAmount: 5,
    expire: 28,
    prime: 2,
    seoSlug: "semglee-days-supply-calculator",
    seoTitle: "Semglee Days Supply Calculator with Priming",
    seoDescription:
      "Calculate Semglee insulin pen days supply including priming doses for pharmacists.",
    seoIntro:
      "Use this Semglee calculator to estimate insulin pen days supply quickly and consistently for dispensing and billing workflow.",
  },
  {
    id: 61,
    name: "Toujeo® SoloStar 3 Pens U-300",
    addToName: "1.5ml per Pen, 4.5ml per Box",
    ndc: "NDC: 0024-5869-03",
    prime: 3,
    unitsInPen: 450,
    expire: 56,
    pensAmount: 3,
    seoSlug: "toujeo-days-supply-calculator",
    seoTitle: "Toujeo Days Supply Calculator with Priming",
    seoDescription:
      "Calculate Toujeo SoloStar insulin pen days supply including priming doses. Designed for pharmacists and pharmacy technicians.",
    seoIntro:
      "Use this Toujeo days supply calculator to estimate insulin pen days supply while accounting for priming, package size, and pharmacy workflow.",
  },
  {
    id: 62,
    name: "Toujeo Max SoloStar 2 Pens U-300 ",
    addToName: "3ml per Pen, 6ml per Box",
    ndc: "NDC: 0024-5871-02",
    prime: 4,
    unitsInPen: 900,
    expire: 56,
    pensAmount: 2,
  },
  {
    id: 63,
    name: "Tresiba FlexTouch 5 Pens U-100",
    addToName: "3ml per Pen, 15ml per Box",
    ndc: "NDC: 0169-2660-15",
    prime: 2,
    unitsInPen: 300,
    expire: 56,
    pensAmount: 5,
    seoSlug: "tresiba-days-supply-calculator",
    seoTitle: "Tresiba Days Supply Calculator with Priming",
    seoDescription:
      "Calculate Tresiba FlexTouch insulin pen days supply including priming doses. Designed for pharmacists and pharmacy technicians.",
    seoIntro:
      "Use this Tresiba days supply calculator to estimate insulin pen days supply while accounting for priming, package size, and real-world dispensing workflow.",
  },
  {
    id: 64,
    name: "Tresiba FlexTouch 3 Pens U-200",
    addToName: "3ml per Pen, 9ml per Box",
    ndc: "NDC: 0169-2550-13",
    prime: 2,
    unitsInPen: 600,
    expire: 56,
    pensAmount: 3,
  },
  {
    id: 65,
    name: "Novolin R FlexPen 5 Pens U-100 ",
    addToName: "3ml per Pen, 15ml per Box",
    ndc: "NDC: 0169-3003-15",
    unitsInPen: 300,
    prime: 2,
    expire: 28,
  },
];

export const medicineData: Medicine[] = rawMedicineData.map((m) => ({
  ...m,
  seoSlug:
    m.seoSlug ??
    m.name
      .toLowerCase()
      .replace(/®|™/g, "")
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "") + "-days-supply-calculator",
}));
